#![allow(non_snake_case)]
#![allow(non_camel_case_types)]
#![allow(non_upper_case_globals)]
#![allow(clippy::all)]
#![deny(clippy::cargo)]

/* automatically generated by rust-bindgen 0.58.1 */

pub const vlFalse: ::std::os::raw::c_uchar = 0;
pub const vlTrue: ::std::os::raw::c_uchar = 1;
pub const VTF_MAJOR_VERSION: u32 = 7;
pub const VTF_MINOR_VERSION: u32 = 5;
pub const VTF_MINOR_VERSION_DEFAULT: u32 = 3;
pub const VTF_MINOR_VERSION_MIN_SPHERE_MAP: u32 = 1;
pub const VTF_MINOR_VERSION_MIN_VOLUME: u32 = 2;
pub const VTF_MINOR_VERSION_MIN_RESOURCE: u32 = 3;
pub const VTF_MINOR_VERSION_MIN_NO_SPHERE_MAP: u32 = 5;
pub type vlBool = ::std::os::raw::c_uchar;
pub type vlChar = ::std::os::raw::c_char;
pub type vlByte = ::std::os::raw::c_uchar;
pub type vlShort = ::std::os::raw::c_short;
pub type vlUShort = ::std::os::raw::c_ushort;
pub type vlInt = ::std::os::raw::c_int;
pub type vlUInt = ::std::os::raw::c_uint;
pub type vlLong = ::std::os::raw::c_long;
pub type vlULong = ::std::os::raw::c_ulong;
pub type vlSingle = f32;
pub type vlDouble = f64;
pub type vlVoid = ::std::os::raw::c_void;
pub type vlFloat = vlSingle;
pub type vlOffset = vlLong;
pub type vlSSize = vlUInt;
pub type vlSize = vlUInt;
pub type vlUInt8 = ::std::os::raw::c_uchar;
pub type vlUInt16 = ::std::os::raw::c_ushort;
pub type vlUInt32 = ::std::os::raw::c_uint;
pub type vlUInt64 = ::std::os::raw::c_ulonglong;
pub const tagVLSeekMode_SEEK_MODE_BEGIN: tagVLSeekMode = 0;
pub const tagVLSeekMode_SEEK_MODE_CURRENT: tagVLSeekMode = 1;
pub const tagVLSeekMode_SEEK_MODE_END: tagVLSeekMode = 2;
pub type tagVLSeekMode = ::std::os::raw::c_int;
#[doc = "!<  = Red, Green, Blue, Alpha - 32 bpp"]
pub const tagVTFImageFormat_IMAGE_FORMAT_RGBA8888: tagVTFImageFormat = 0;
#[doc = "!<  = Alpha, Blue, Green, Red - 32 bpp"]
pub const tagVTFImageFormat_IMAGE_FORMAT_ABGR8888: tagVTFImageFormat = 1;
#[doc = "!<  = Red, Green, Blue - 24 bpp"]
pub const tagVTFImageFormat_IMAGE_FORMAT_RGB888: tagVTFImageFormat = 2;
#[doc = "!<  = Blue, Green, Red - 24 bpp"]
pub const tagVTFImageFormat_IMAGE_FORMAT_BGR888: tagVTFImageFormat = 3;
#[doc = "!<  = Red, Green, Blue - 16 bpp"]
pub const tagVTFImageFormat_IMAGE_FORMAT_RGB565: tagVTFImageFormat = 4;
#[doc = "!<  = Luminance - 8 bpp"]
pub const tagVTFImageFormat_IMAGE_FORMAT_I8: tagVTFImageFormat = 5;
#[doc = "!<  = Luminance, Alpha - 16 bpp"]
pub const tagVTFImageFormat_IMAGE_FORMAT_IA88: tagVTFImageFormat = 6;
#[doc = "!<  = Paletted - 8 bpp"]
pub const tagVTFImageFormat_IMAGE_FORMAT_P8: tagVTFImageFormat = 7;
#[doc = "!<  = Alpha- 8 bpp"]
pub const tagVTFImageFormat_IMAGE_FORMAT_A8: tagVTFImageFormat = 8;
#[doc = "!<  = Red, Green, Blue, \"BlueScreen\" Alpha - 24 bpp"]
pub const tagVTFImageFormat_IMAGE_FORMAT_RGB888_BLUESCREEN: tagVTFImageFormat = 9;
#[doc = "!<  = Red, Green, Blue, \"BlueScreen\" Alpha - 24 bpp"]
pub const tagVTFImageFormat_IMAGE_FORMAT_BGR888_BLUESCREEN: tagVTFImageFormat = 10;
#[doc = "!<  = Alpha, Red, Green, Blue - 32 bpp"]
pub const tagVTFImageFormat_IMAGE_FORMAT_ARGB8888: tagVTFImageFormat = 11;
#[doc = "!<  = Blue, Green, Red, Alpha - 32 bpp"]
pub const tagVTFImageFormat_IMAGE_FORMAT_BGRA8888: tagVTFImageFormat = 12;
#[doc = "!<  = DXT1 compressed format - 4 bpp"]
pub const tagVTFImageFormat_IMAGE_FORMAT_DXT1: tagVTFImageFormat = 13;
#[doc = "!<  = DXT3 compressed format - 8 bpp"]
pub const tagVTFImageFormat_IMAGE_FORMAT_DXT3: tagVTFImageFormat = 14;
#[doc = "!<  = DXT5 compressed format - 8 bpp"]
pub const tagVTFImageFormat_IMAGE_FORMAT_DXT5: tagVTFImageFormat = 15;
#[doc = "!<  = Blue, Green, Red, Unused - 32 bpp"]
pub const tagVTFImageFormat_IMAGE_FORMAT_BGRX8888: tagVTFImageFormat = 16;
#[doc = "!<  = Blue, Green, Red - 16 bpp"]
pub const tagVTFImageFormat_IMAGE_FORMAT_BGR565: tagVTFImageFormat = 17;
#[doc = "!<  = Blue, Green, Red, Unused - 16 bpp"]
pub const tagVTFImageFormat_IMAGE_FORMAT_BGRX5551: tagVTFImageFormat = 18;
#[doc = "!<  = Red, Green, Blue, Alpha - 16 bpp"]
pub const tagVTFImageFormat_IMAGE_FORMAT_BGRA4444: tagVTFImageFormat = 19;
#[doc = "!<  = DXT1 compressed format with 1-bit alpha - 4 bpp"]
pub const tagVTFImageFormat_IMAGE_FORMAT_DXT1_ONEBITALPHA: tagVTFImageFormat = 20;
#[doc = "!<  = Blue, Green, Red, Alpha - 16 bpp"]
pub const tagVTFImageFormat_IMAGE_FORMAT_BGRA5551: tagVTFImageFormat = 21;
#[doc = "!<  = 2 channel format for DuDv/Normal maps - 16 bpp"]
pub const tagVTFImageFormat_IMAGE_FORMAT_UV88: tagVTFImageFormat = 22;
#[doc = "!<  = 4 channel format for DuDv/Normal maps - 32 bpp"]
pub const tagVTFImageFormat_IMAGE_FORMAT_UVWQ8888: tagVTFImageFormat = 23;
#[doc = "!<  = Red, Green, Blue, Alpha - 64 bpp"]
pub const tagVTFImageFormat_IMAGE_FORMAT_RGBA16161616F: tagVTFImageFormat = 24;
#[doc = "!<  = Red, Green, Blue, Alpha signed with mantissa - 64 bpp"]
pub const tagVTFImageFormat_IMAGE_FORMAT_RGBA16161616: tagVTFImageFormat = 25;
#[doc = "!<  = 4 channel format for DuDv/Normal maps - 32 bpp"]
pub const tagVTFImageFormat_IMAGE_FORMAT_UVLX8888: tagVTFImageFormat = 26;
#[doc = "!<  = Luminance - 32 bpp"]
pub const tagVTFImageFormat_IMAGE_FORMAT_R32F: tagVTFImageFormat = 27;
#[doc = "!<  = Red, Green, Blue - 96 bpp"]
pub const tagVTFImageFormat_IMAGE_FORMAT_RGB323232F: tagVTFImageFormat = 28;
#[doc = "!<  = Red, Green, Blue, Alpha - 128 bpp"]
pub const tagVTFImageFormat_IMAGE_FORMAT_RGBA32323232F: tagVTFImageFormat = 29;
pub const tagVTFImageFormat_IMAGE_FORMAT_NV_DST16: tagVTFImageFormat = 30;
pub const tagVTFImageFormat_IMAGE_FORMAT_NV_DST24: tagVTFImageFormat = 31;
pub const tagVTFImageFormat_IMAGE_FORMAT_NV_INTZ: tagVTFImageFormat = 32;
pub const tagVTFImageFormat_IMAGE_FORMAT_NV_RAWZ: tagVTFImageFormat = 33;
pub const tagVTFImageFormat_IMAGE_FORMAT_ATI_DST16: tagVTFImageFormat = 34;
pub const tagVTFImageFormat_IMAGE_FORMAT_ATI_DST24: tagVTFImageFormat = 35;
pub const tagVTFImageFormat_IMAGE_FORMAT_NV_NULL: tagVTFImageFormat = 36;
pub const tagVTFImageFormat_IMAGE_FORMAT_ATI2N: tagVTFImageFormat = 37;
pub const tagVTFImageFormat_IMAGE_FORMAT_ATI1N: tagVTFImageFormat = 38;
pub const tagVTFImageFormat_IMAGE_FORMAT_COUNT: tagVTFImageFormat = 39;
pub const tagVTFImageFormat_IMAGE_FORMAT_NONE: tagVTFImageFormat = -1;
#[doc = "! Image data formats VTFLib supports.\n*!\nImage data formats supported by VTFLib. Details show colour channel order, plus number\nof bits per-pixel.\n\\note \"Bluescreen\" alpha uses any pixel with an pixel of R0, G0, B255 as transparent.\n*/"]
pub type tagVTFImageFormat = ::std::os::raw::c_int;
#[doc = "! Image data formats VTFLib supports.\n*!\nImage data formats supported by VTFLib. Details show colour channel order, plus number\nof bits per-pixel.\n\\note \"Bluescreen\" alpha uses any pixel with an pixel of R0, G0, B255 as transparent.\n*/"]
pub use self::tagVTFImageFormat as VTFImageFormat;
pub const tagVTFImageFlag_TEXTUREFLAGS_POINTSAMPLE: tagVTFImageFlag = 1;
pub const tagVTFImageFlag_TEXTUREFLAGS_TRILINEAR: tagVTFImageFlag = 2;
pub const tagVTFImageFlag_TEXTUREFLAGS_CLAMPS: tagVTFImageFlag = 4;
pub const tagVTFImageFlag_TEXTUREFLAGS_CLAMPT: tagVTFImageFlag = 8;
pub const tagVTFImageFlag_TEXTUREFLAGS_ANISOTROPIC: tagVTFImageFlag = 16;
pub const tagVTFImageFlag_TEXTUREFLAGS_HINT_DXT5: tagVTFImageFlag = 32;
pub const tagVTFImageFlag_TEXTUREFLAGS_SRGB: tagVTFImageFlag = 64;
pub const tagVTFImageFlag_TEXTUREFLAGS_DEPRECATED_NOCOMPRESS: tagVTFImageFlag = 64;
pub const tagVTFImageFlag_TEXTUREFLAGS_NORMAL: tagVTFImageFlag = 128;
pub const tagVTFImageFlag_TEXTUREFLAGS_NOMIP: tagVTFImageFlag = 256;
pub const tagVTFImageFlag_TEXTUREFLAGS_NOLOD: tagVTFImageFlag = 512;
pub const tagVTFImageFlag_TEXTUREFLAGS_MINMIP: tagVTFImageFlag = 1024;
pub const tagVTFImageFlag_TEXTUREFLAGS_PROCEDURAL: tagVTFImageFlag = 2048;
#[doc = "!< Automatically generated by VTex."]
pub const tagVTFImageFlag_TEXTUREFLAGS_ONEBITALPHA: tagVTFImageFlag = 4096;
#[doc = "!< Automatically generated by VTex."]
pub const tagVTFImageFlag_TEXTUREFLAGS_EIGHTBITALPHA: tagVTFImageFlag = 8192;
pub const tagVTFImageFlag_TEXTUREFLAGS_ENVMAP: tagVTFImageFlag = 16384;
pub const tagVTFImageFlag_TEXTUREFLAGS_RENDERTARGET: tagVTFImageFlag = 32768;
pub const tagVTFImageFlag_TEXTUREFLAGS_DEPTHRENDERTARGET: tagVTFImageFlag = 65536;
pub const tagVTFImageFlag_TEXTUREFLAGS_NODEBUGOVERRIDE: tagVTFImageFlag = 131072;
pub const tagVTFImageFlag_TEXTUREFLAGS_SINGLECOPY: tagVTFImageFlag = 262144;
#[doc = "!< Originally internal to VTex as TEXTUREFLAGS_ONEOVERMIPLEVELINALPHA."]
pub const tagVTFImageFlag_TEXTUREFLAGS_UNUSED0: tagVTFImageFlag = 524288;
pub const tagVTFImageFlag_TEXTUREFLAGS_DEPRECATED_ONEOVERMIPLEVELINALPHA: tagVTFImageFlag = 524288;
#[doc = "!< Originally internal to VTex as TEXTUREFLAGS_PREMULTCOLORBYONEOVERMIPLEVEL."]
pub const tagVTFImageFlag_TEXTUREFLAGS_UNUSED1: tagVTFImageFlag = 1048576;
pub const tagVTFImageFlag_TEXTUREFLAGS_DEPRECATED_PREMULTCOLORBYONEOVERMIPLEVEL: tagVTFImageFlag =
    1048576;
#[doc = "!< Originally internal to VTex as TEXTUREFLAGS_NORMALTODUDV."]
pub const tagVTFImageFlag_TEXTUREFLAGS_UNUSED2: tagVTFImageFlag = 2097152;
pub const tagVTFImageFlag_TEXTUREFLAGS_DEPRECATED_NORMALTODUDV: tagVTFImageFlag = 2097152;
#[doc = "!< Originally internal to VTex as TEXTUREFLAGS_ALPHATESTMIPGENERATION."]
pub const tagVTFImageFlag_TEXTUREFLAGS_UNUSED3: tagVTFImageFlag = 4194304;
pub const tagVTFImageFlag_TEXTUREFLAGS_DEPRECATED_ALPHATESTMIPGENERATION: tagVTFImageFlag = 4194304;
pub const tagVTFImageFlag_TEXTUREFLAGS_NODEPTHBUFFER: tagVTFImageFlag = 8388608;
#[doc = "!< Originally internal to VTex as TEXTUREFLAGS_NICEFILTERED."]
pub const tagVTFImageFlag_TEXTUREFLAGS_UNUSED4: tagVTFImageFlag = 16777216;
pub const tagVTFImageFlag_TEXTUREFLAGS_DEPRECATED_NICEFILTERED: tagVTFImageFlag = 16777216;
pub const tagVTFImageFlag_TEXTUREFLAGS_CLAMPU: tagVTFImageFlag = 33554432;
pub const tagVTFImageFlag_TEXTUREFLAGS_VERTEXTEXTURE: tagVTFImageFlag = 67108864;
pub const tagVTFImageFlag_TEXTUREFLAGS_SSBUMP: tagVTFImageFlag = 134217728;
#[doc = "!< Originally TEXTUREFLAGS_UNFILTERABLE_OK."]
pub const tagVTFImageFlag_TEXTUREFLAGS_UNUSED5: tagVTFImageFlag = 268435456;
pub const tagVTFImageFlag_TEXTUREFLAGS_DEPRECATED_UNFILTERABLE_OK: tagVTFImageFlag = 268435456;
pub const tagVTFImageFlag_TEXTUREFLAGS_BORDER: tagVTFImageFlag = 536870912;
pub const tagVTFImageFlag_TEXTUREFLAGS_DEPRECATED_SPECVAR_RED: tagVTFImageFlag = 1073741824;
pub const tagVTFImageFlag_TEXTUREFLAGS_DEPRECATED_SPECVAR_ALPHA: tagVTFImageFlag = -2147483648;
pub const tagVTFImageFlag_TEXTUREFLAGS_LAST: tagVTFImageFlag = 536870912;
pub const tagVTFImageFlag_TEXTUREFLAGS_COUNT: tagVTFImageFlag = 30;
#[doc = "! VTF image header flags."]
pub type tagVTFImageFlag = ::std::os::raw::c_int;
#[doc = "! VTF image header flags."]
pub use self::tagVTFImageFlag as VTFImageFlag;
pub const tagVTFCubeMapFace_CUBEMAP_FACE_RIGHT: tagVTFCubeMapFace = 0;
pub const tagVTFCubeMapFace_CUBEMAP_FACE_LEFT: tagVTFCubeMapFace = 1;
pub const tagVTFCubeMapFace_CUBEMAP_FACE_BACK: tagVTFCubeMapFace = 2;
pub const tagVTFCubeMapFace_CUBEMAP_FACE_FRONT: tagVTFCubeMapFace = 3;
pub const tagVTFCubeMapFace_CUBEMAP_FACE_UP: tagVTFCubeMapFace = 4;
pub const tagVTFCubeMapFace_CUBEMAP_FACE_DOWN: tagVTFCubeMapFace = 5;
pub const tagVTFCubeMapFace_CUBEMAP_FACE_SphereMap: tagVTFCubeMapFace = 6;
pub const tagVTFCubeMapFace_CUBEMAP_FACE_COUNT: tagVTFCubeMapFace = 7;
#[doc = "! VTF image cubemap face indices."]
pub type tagVTFCubeMapFace = ::std::os::raw::c_int;
#[doc = "! VTF image cubemap face indices."]
pub use self::tagVTFCubeMapFace as VTFCubeMapFace;
pub const tagVTFMipmapFilter_MIPMAP_FILTER_POINT: tagVTFMipmapFilter = 0;
pub const tagVTFMipmapFilter_MIPMAP_FILTER_BOX: tagVTFMipmapFilter = 1;
pub const tagVTFMipmapFilter_MIPMAP_FILTER_TRIANGLE: tagVTFMipmapFilter = 2;
pub const tagVTFMipmapFilter_MIPMAP_FILTER_QUADRATIC: tagVTFMipmapFilter = 3;
pub const tagVTFMipmapFilter_MIPMAP_FILTER_CUBIC: tagVTFMipmapFilter = 4;
pub const tagVTFMipmapFilter_MIPMAP_FILTER_CATROM: tagVTFMipmapFilter = 5;
pub const tagVTFMipmapFilter_MIPMAP_FILTER_MITCHELL: tagVTFMipmapFilter = 6;
pub const tagVTFMipmapFilter_MIPMAP_FILTER_GAUSSIAN: tagVTFMipmapFilter = 7;
pub const tagVTFMipmapFilter_MIPMAP_FILTER_SINC: tagVTFMipmapFilter = 8;
pub const tagVTFMipmapFilter_MIPMAP_FILTER_BESSEL: tagVTFMipmapFilter = 9;
pub const tagVTFMipmapFilter_MIPMAP_FILTER_HANNING: tagVTFMipmapFilter = 10;
pub const tagVTFMipmapFilter_MIPMAP_FILTER_HAMMING: tagVTFMipmapFilter = 11;
pub const tagVTFMipmapFilter_MIPMAP_FILTER_BLACKMAN: tagVTFMipmapFilter = 12;
pub const tagVTFMipmapFilter_MIPMAP_FILTER_KAISER: tagVTFMipmapFilter = 13;
pub const tagVTFMipmapFilter_MIPMAP_FILTER_COUNT: tagVTFMipmapFilter = 14;
#[doc = "! MIP map reduction filter indices."]
pub type tagVTFMipmapFilter = ::std::os::raw::c_int;
#[doc = "! MIP map reduction filter indices."]
pub use self::tagVTFMipmapFilter as VTFMipmapFilter;
pub const tagVTFSharpenFilter_SHARPEN_FILTER_NONE: tagVTFSharpenFilter = 0;
pub const tagVTFSharpenFilter_SHARPEN_FILTER_NEGATIVE: tagVTFSharpenFilter = 1;
pub const tagVTFSharpenFilter_SHARPEN_FILTER_LIGHTER: tagVTFSharpenFilter = 2;
pub const tagVTFSharpenFilter_SHARPEN_FILTER_DARKER: tagVTFSharpenFilter = 3;
pub const tagVTFSharpenFilter_SHARPEN_FILTER_CONTRASTMORE: tagVTFSharpenFilter = 4;
pub const tagVTFSharpenFilter_SHARPEN_FILTER_CONTRASTLESS: tagVTFSharpenFilter = 5;
pub const tagVTFSharpenFilter_SHARPEN_FILTER_SMOOTHEN: tagVTFSharpenFilter = 6;
pub const tagVTFSharpenFilter_SHARPEN_FILTER_SHARPENSOFT: tagVTFSharpenFilter = 7;
pub const tagVTFSharpenFilter_SHARPEN_FILTER_SHARPENMEDIUM: tagVTFSharpenFilter = 8;
pub const tagVTFSharpenFilter_SHARPEN_FILTER_SHARPENSTRONG: tagVTFSharpenFilter = 9;
pub const tagVTFSharpenFilter_SHARPEN_FILTER_FINDEDGES: tagVTFSharpenFilter = 10;
pub const tagVTFSharpenFilter_SHARPEN_FILTER_CONTOUR: tagVTFSharpenFilter = 11;
pub const tagVTFSharpenFilter_SHARPEN_FILTER_EDGEDETECT: tagVTFSharpenFilter = 12;
pub const tagVTFSharpenFilter_SHARPEN_FILTER_EDGEDETECTSOFT: tagVTFSharpenFilter = 13;
pub const tagVTFSharpenFilter_SHARPEN_FILTER_EMBOSS: tagVTFSharpenFilter = 14;
pub const tagVTFSharpenFilter_SHARPEN_FILTER_MEANREMOVAL: tagVTFSharpenFilter = 15;
pub const tagVTFSharpenFilter_SHARPEN_FILTER_UNSHARP: tagVTFSharpenFilter = 16;
pub const tagVTFSharpenFilter_SHARPEN_FILTER_XSHARPEN: tagVTFSharpenFilter = 17;
pub const tagVTFSharpenFilter_SHARPEN_FILTER_WARPSHARP: tagVTFSharpenFilter = 18;
pub const tagVTFSharpenFilter_SHARPEN_FILTER_COUNT: tagVTFSharpenFilter = 19;
#[doc = "! MIP map sharpen filter indices."]
pub type tagVTFSharpenFilter = ::std::os::raw::c_int;
#[doc = "! MIP map sharpen filter indices."]
pub use self::tagVTFSharpenFilter as VTFSharpenFilter;
pub const tagDXTQuality_DXT_QUALITY_LOW: tagDXTQuality = 0;
pub const tagDXTQuality_DXT_QUALITY_MEDIUM: tagDXTQuality = 1;
pub const tagDXTQuality_DXT_QUALITY_HIGH: tagDXTQuality = 2;
pub const tagDXTQuality_DXT_QUALITY_HIGHEST: tagDXTQuality = 3;
pub const tagDXTQuality_DXT_QUALITY_COUNT: tagDXTQuality = 4;
pub type tagDXTQuality = ::std::os::raw::c_int;
pub use self::tagDXTQuality as VTFDXTQuality;
pub const tagVTFKernelFilter_KERNEL_FILTER_4X: tagVTFKernelFilter = 0;
pub const tagVTFKernelFilter_KERNEL_FILTER_3X3: tagVTFKernelFilter = 1;
pub const tagVTFKernelFilter_KERNEL_FILTER_5X5: tagVTFKernelFilter = 2;
pub const tagVTFKernelFilter_KERNEL_FILTER_7X7: tagVTFKernelFilter = 3;
pub const tagVTFKernelFilter_KERNEL_FILTER_9X9: tagVTFKernelFilter = 4;
pub const tagVTFKernelFilter_KERNEL_FILTER_DUDV: tagVTFKernelFilter = 5;
pub const tagVTFKernelFilter_KERNEL_FILTER_COUNT: tagVTFKernelFilter = 6;
#[doc = "! Normal map creation kernel size indices."]
pub type tagVTFKernelFilter = ::std::os::raw::c_int;
#[doc = "! Normal map creation kernel size indices."]
pub use self::tagVTFKernelFilter as VTFKernelFilter;
pub const tagVTFHeightConversionMethod_HEIGHT_CONVERSION_METHOD_ALPHA:
    tagVTFHeightConversionMethod = 0;
pub const tagVTFHeightConversionMethod_HEIGHT_CONVERSION_METHOD_AVERAGE_RGB:
    tagVTFHeightConversionMethod = 1;
pub const tagVTFHeightConversionMethod_HEIGHT_CONVERSION_METHOD_BIASED_RGB:
    tagVTFHeightConversionMethod = 2;
pub const tagVTFHeightConversionMethod_HEIGHT_CONVERSION_METHOD_RED: tagVTFHeightConversionMethod =
    3;
pub const tagVTFHeightConversionMethod_HEIGHT_CONVERSION_METHOD_GREEN:
    tagVTFHeightConversionMethod = 4;
pub const tagVTFHeightConversionMethod_HEIGHT_CONVERSION_METHOD_BLUE: tagVTFHeightConversionMethod =
    5;
pub const tagVTFHeightConversionMethod_HEIGHT_CONVERSION_METHOD_MAX_RGB:
    tagVTFHeightConversionMethod = 6;
pub const tagVTFHeightConversionMethod_HEIGHT_CONVERSION_METHOD_COLORSPACE:
    tagVTFHeightConversionMethod = 7;
pub const tagVTFHeightConversionMethod_HEIGHT_CONVERSION_METHOD_COUNT:
    tagVTFHeightConversionMethod = 8;
#[doc = "! Normal map height conversion method indices."]
pub type tagVTFHeightConversionMethod = ::std::os::raw::c_int;
#[doc = "! Normal map height conversion method indices."]
pub use self::tagVTFHeightConversionMethod as VTFHeightConversionMethod;
pub const tagVTFNormalAlphaResult_NORMAL_ALPHA_RESULT_NOCHANGE: tagVTFNormalAlphaResult = 0;
pub const tagVTFNormalAlphaResult_NORMAL_ALPHA_RESULT_HEIGHT: tagVTFNormalAlphaResult = 1;
pub const tagVTFNormalAlphaResult_NORMAL_ALPHA_RESULT_BLACK: tagVTFNormalAlphaResult = 2;
pub const tagVTFNormalAlphaResult_NORMAL_ALPHA_RESULT_WHITE: tagVTFNormalAlphaResult = 3;
pub const tagVTFNormalAlphaResult_NORMAL_ALPHA_RESULT_COUNT: tagVTFNormalAlphaResult = 4;
#[doc = "! Normal map alpha channel handling indices."]
pub type tagVTFNormalAlphaResult = ::std::os::raw::c_int;
#[doc = "! Normal map alpha channel handling indices."]
pub use self::tagVTFNormalAlphaResult as VTFNormalAlphaResult;
pub const tagVTFResizeMethod_RESIZE_NEAREST_POWER2: tagVTFResizeMethod = 0;
pub const tagVTFResizeMethod_RESIZE_BIGGEST_POWER2: tagVTFResizeMethod = 1;
pub const tagVTFResizeMethod_RESIZE_SMALLEST_POWER2: tagVTFResizeMethod = 2;
pub const tagVTFResizeMethod_RESIZE_SET: tagVTFResizeMethod = 3;
pub const tagVTFResizeMethod_RESIZE_COUNT: tagVTFResizeMethod = 4;
#[doc = "! Image re-size handling method indices."]
pub type tagVTFResizeMethod = ::std::os::raw::c_int;
#[doc = "! Image re-size handling method indices."]
pub use self::tagVTFResizeMethod as VTFResizeMethod;
pub const tagVTFLookDir_LOOK_DOWN_X: tagVTFLookDir = 0;
pub const tagVTFLookDir_LOOK_DOWN_NEGX: tagVTFLookDir = 1;
pub const tagVTFLookDir_LOOK_DOWN_Y: tagVTFLookDir = 2;
pub const tagVTFLookDir_LOOK_DOWN_NEGY: tagVTFLookDir = 3;
pub const tagVTFLookDir_LOOK_DOWN_Z: tagVTFLookDir = 4;
pub const tagVTFLookDir_LOOK_DOWN_NEGZ: tagVTFLookDir = 5;
#[doc = "! Spheremap creation look direction indices."]
pub type tagVTFLookDir = ::std::os::raw::c_int;
#[doc = "! Spheremap creation look direction indices."]
pub use self::tagVTFLookDir as VTFLookDir;
pub const tagVTFResourceEntryTypeFlag_RSRCF_HAS_NO_DATA_CHUNK: tagVTFResourceEntryTypeFlag = 2;
#[doc = "! Resource entry type flags."]
pub type tagVTFResourceEntryTypeFlag = ::std::os::raw::c_int;
#[doc = "! Resource entry type flags."]
pub use self::tagVTFResourceEntryTypeFlag as VTFResourceEntryTypeFlag;
pub const tagVTFResourceEntryType_VTF_LEGACY_RSRC_LOW_RES_IMAGE: tagVTFResourceEntryType = 1;
pub const tagVTFResourceEntryType_VTF_LEGACY_RSRC_IMAGE: tagVTFResourceEntryType = 48;
pub const tagVTFResourceEntryType_VTF_RSRC_SHEET: tagVTFResourceEntryType = 16;
pub const tagVTFResourceEntryType_VTF_RSRC_CRC: tagVTFResourceEntryType = 37966403;
pub const tagVTFResourceEntryType_VTF_RSRC_TEXTURE_LOD_SETTINGS: tagVTFResourceEntryType = 38031180;
pub const tagVTFResourceEntryType_VTF_RSRC_TEXTURE_SETTINGS_EX: tagVTFResourceEntryType = 38753108;
pub const tagVTFResourceEntryType_VTF_RSRC_KEY_VALUE_DATA: tagVTFResourceEntryType = 4478539;
pub const tagVTFResourceEntryType_VTF_RSRC_MAX_DICTIONARY_ENTRIES: tagVTFResourceEntryType = 32;
#[doc = "! Resource entry type idendifiers."]
pub type tagVTFResourceEntryType = ::std::os::raw::c_int;
#[doc = "! Resource entry type idendifiers."]
pub use self::tagVTFResourceEntryType as VTFResourceEntryType;
#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct tagSVTFImageFormatInfo {
    #[doc = "!< Enumeration text equivalent."]
    pub lpName: *const vlChar,
    #[doc = "!< Format bits per pixel."]
    pub uiBitsPerPixel: vlUInt,
    #[doc = "!< Format bytes per pixel."]
    pub uiBytesPerPixel: vlUInt,
    #[doc = "!< Format red bits per pixel.  0 for N/A."]
    pub uiRedBitsPerPixel: vlUInt,
    #[doc = "!< Format green bits per pixel.  0 for N/A."]
    pub uiGreenBitsPerPixel: vlUInt,
    #[doc = "!< Format blue bits per pixel.  0 for N/A."]
    pub uiBlueBitsPerPixel: vlUInt,
    #[doc = "!< Format alpha bits per pixel.  0 for N/A."]
    pub uiAlphaBitsPerPixel: vlUInt,
    #[doc = "!< Format is compressed (DXT)."]
    pub bIsCompressed: vlBool,
    #[doc = "!< Format is supported by VTFLib."]
    pub bIsSupported: vlBool,
}
#[test]
fn bindgen_test_layout_tagSVTFImageFormatInfo() {
    const UNINIT: ::std::mem::MaybeUninit<tagSVTFImageFormatInfo> =
        ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<tagSVTFImageFormatInfo>(),
        34usize,
        concat!("Size of: ", stringify!(tagSVTFImageFormatInfo))
    );
    assert_eq!(
        ::std::mem::align_of::<tagSVTFImageFormatInfo>(),
        1usize,
        concat!("Alignment of ", stringify!(tagSVTFImageFormatInfo))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).lpName) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(tagSVTFImageFormatInfo),
            "::",
            stringify!(lpName)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).uiBitsPerPixel) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(tagSVTFImageFormatInfo),
            "::",
            stringify!(uiBitsPerPixel)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).uiBytesPerPixel) as usize - ptr as usize },
        12usize,
        concat!(
            "Offset of field: ",
            stringify!(tagSVTFImageFormatInfo),
            "::",
            stringify!(uiBytesPerPixel)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).uiRedBitsPerPixel) as usize - ptr as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(tagSVTFImageFormatInfo),
            "::",
            stringify!(uiRedBitsPerPixel)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).uiGreenBitsPerPixel) as usize - ptr as usize },
        20usize,
        concat!(
            "Offset of field: ",
            stringify!(tagSVTFImageFormatInfo),
            "::",
            stringify!(uiGreenBitsPerPixel)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).uiBlueBitsPerPixel) as usize - ptr as usize },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(tagSVTFImageFormatInfo),
            "::",
            stringify!(uiBlueBitsPerPixel)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).uiAlphaBitsPerPixel) as usize - ptr as usize },
        28usize,
        concat!(
            "Offset of field: ",
            stringify!(tagSVTFImageFormatInfo),
            "::",
            stringify!(uiAlphaBitsPerPixel)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).bIsCompressed) as usize - ptr as usize },
        32usize,
        concat!(
            "Offset of field: ",
            stringify!(tagSVTFImageFormatInfo),
            "::",
            stringify!(bIsCompressed)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).bIsSupported) as usize - ptr as usize },
        33usize,
        concat!(
            "Offset of field: ",
            stringify!(tagSVTFImageFormatInfo),
            "::",
            stringify!(bIsSupported)
        )
    );
}
pub type SVTFImageFormatInfo = tagSVTFImageFormatInfo;
#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct tagSVTFCreateOptions {
    #[doc = "!< Output image version."]
    pub uiVersion: [vlUInt; 2usize],
    #[doc = "!< Output image output storage format."]
    pub ImageFormat: VTFImageFormat,
    #[doc = "!< Output image header flags."]
    pub uiFlags: vlUInt,
    #[doc = "!< Output image start frame."]
    pub uiStartFrame: vlUInt,
    #[doc = "!< Output image bump scale."]
    pub sBumpScale: vlSingle,
    #[doc = "!< Output image reflectivity. (Only used if bReflectivity is false.)"]
    pub sReflectivity: [vlSingle; 3usize],
    #[doc = "!< Generate MIPmaps. (Space is always allocated.)"]
    pub bMipmaps: vlBool,
    #[doc = "!< MIP map re-size filter."]
    pub MipmapFilter: VTFMipmapFilter,
    #[doc = "!< MIP map sharpen filter."]
    pub MipmapSharpenFilter: VTFSharpenFilter,
    #[doc = "!< Generate thumbnail image."]
    pub bThumbnail: vlBool,
    #[doc = "!< Compute image reflectivity."]
    pub bReflectivity: vlBool,
    #[doc = "!< Resize the input image."]
    pub bResize: vlBool,
    #[doc = "!< New size compution method."]
    pub ResizeMethod: VTFResizeMethod,
    #[doc = "!< Re-size filter."]
    pub ResizeFilter: VTFMipmapFilter,
    #[doc = "!< Sharpen filter."]
    pub ResizeSharpenFilter: VTFSharpenFilter,
    #[doc = "!< New width after re-size if method is RESIZE_SET."]
    pub uiResizeWidth: vlUInt,
    #[doc = "!< New height after re-size if method is RESIZE_SET."]
    pub uiResizeHeight: vlUInt,
    #[doc = "!< Clamp re-size size."]
    pub bResizeClamp: vlBool,
    #[doc = "!< Maximum width to re-size to."]
    pub uiResizeClampWidth: vlUInt,
    #[doc = "!< Maximum height to re-size to."]
    pub uiResizeClampHeight: vlUInt,
    #[doc = "!< Gamma correct input image."]
    pub bGammaCorrection: vlBool,
    #[doc = "!< Gamma correction to apply."]
    pub sGammaCorrection: vlSingle,
    #[doc = "!< Convert input image to a normal map."]
    pub bNormalMap: vlBool,
    #[doc = "!< Normal map generation kernel."]
    pub KernelFilter: VTFKernelFilter,
    #[doc = "!< Method or determining height from input image during normal map creation."]
    pub HeightConversionMethod: VTFHeightConversionMethod,
    #[doc = "!< How to handle output image alpha channel, post normal map creation."]
    pub NormalAlphaResult: VTFNormalAlphaResult,
    #[doc = "!< Minimum normal Z value."]
    pub bNormalMinimumZ: vlByte,
    #[doc = "!< Normal map scale."]
    pub sNormalScale: vlSingle,
    #[doc = "!< Wrap the normal map."]
    pub bNormalWrap: vlBool,
    #[doc = "!< Invert the normal X component."]
    pub bNormalInvertX: vlBool,
    #[doc = "!< Invert the normal Y component."]
    pub bNormalInvertY: vlBool,
    #[doc = "!< Invert the normal Z component."]
    pub bNormalInvertZ: vlBool,
    #[doc = "!< Generate a sphere map for six faced environment maps."]
    pub bSphereMap: vlBool,
}
#[test]
fn bindgen_test_layout_tagSVTFCreateOptions() {
    const UNINIT: ::std::mem::MaybeUninit<tagSVTFCreateOptions> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<tagSVTFCreateOptions>(),
        105usize,
        concat!("Size of: ", stringify!(tagSVTFCreateOptions))
    );
    assert_eq!(
        ::std::mem::align_of::<tagSVTFCreateOptions>(),
        1usize,
        concat!("Alignment of ", stringify!(tagSVTFCreateOptions))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).uiVersion) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(tagSVTFCreateOptions),
            "::",
            stringify!(uiVersion)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).ImageFormat) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(tagSVTFCreateOptions),
            "::",
            stringify!(ImageFormat)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).uiFlags) as usize - ptr as usize },
        12usize,
        concat!(
            "Offset of field: ",
            stringify!(tagSVTFCreateOptions),
            "::",
            stringify!(uiFlags)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).uiStartFrame) as usize - ptr as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(tagSVTFCreateOptions),
            "::",
            stringify!(uiStartFrame)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).sBumpScale) as usize - ptr as usize },
        20usize,
        concat!(
            "Offset of field: ",
            stringify!(tagSVTFCreateOptions),
            "::",
            stringify!(sBumpScale)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).sReflectivity) as usize - ptr as usize },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(tagSVTFCreateOptions),
            "::",
            stringify!(sReflectivity)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).bMipmaps) as usize - ptr as usize },
        36usize,
        concat!(
            "Offset of field: ",
            stringify!(tagSVTFCreateOptions),
            "::",
            stringify!(bMipmaps)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).MipmapFilter) as usize - ptr as usize },
        37usize,
        concat!(
            "Offset of field: ",
            stringify!(tagSVTFCreateOptions),
            "::",
            stringify!(MipmapFilter)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).MipmapSharpenFilter) as usize - ptr as usize },
        41usize,
        concat!(
            "Offset of field: ",
            stringify!(tagSVTFCreateOptions),
            "::",
            stringify!(MipmapSharpenFilter)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).bThumbnail) as usize - ptr as usize },
        45usize,
        concat!(
            "Offset of field: ",
            stringify!(tagSVTFCreateOptions),
            "::",
            stringify!(bThumbnail)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).bReflectivity) as usize - ptr as usize },
        46usize,
        concat!(
            "Offset of field: ",
            stringify!(tagSVTFCreateOptions),
            "::",
            stringify!(bReflectivity)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).bResize) as usize - ptr as usize },
        47usize,
        concat!(
            "Offset of field: ",
            stringify!(tagSVTFCreateOptions),
            "::",
            stringify!(bResize)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).ResizeMethod) as usize - ptr as usize },
        48usize,
        concat!(
            "Offset of field: ",
            stringify!(tagSVTFCreateOptions),
            "::",
            stringify!(ResizeMethod)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).ResizeFilter) as usize - ptr as usize },
        52usize,
        concat!(
            "Offset of field: ",
            stringify!(tagSVTFCreateOptions),
            "::",
            stringify!(ResizeFilter)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).ResizeSharpenFilter) as usize - ptr as usize },
        56usize,
        concat!(
            "Offset of field: ",
            stringify!(tagSVTFCreateOptions),
            "::",
            stringify!(ResizeSharpenFilter)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).uiResizeWidth) as usize - ptr as usize },
        60usize,
        concat!(
            "Offset of field: ",
            stringify!(tagSVTFCreateOptions),
            "::",
            stringify!(uiResizeWidth)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).uiResizeHeight) as usize - ptr as usize },
        64usize,
        concat!(
            "Offset of field: ",
            stringify!(tagSVTFCreateOptions),
            "::",
            stringify!(uiResizeHeight)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).bResizeClamp) as usize - ptr as usize },
        68usize,
        concat!(
            "Offset of field: ",
            stringify!(tagSVTFCreateOptions),
            "::",
            stringify!(bResizeClamp)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).uiResizeClampWidth) as usize - ptr as usize },
        69usize,
        concat!(
            "Offset of field: ",
            stringify!(tagSVTFCreateOptions),
            "::",
            stringify!(uiResizeClampWidth)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).uiResizeClampHeight) as usize - ptr as usize },
        73usize,
        concat!(
            "Offset of field: ",
            stringify!(tagSVTFCreateOptions),
            "::",
            stringify!(uiResizeClampHeight)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).bGammaCorrection) as usize - ptr as usize },
        77usize,
        concat!(
            "Offset of field: ",
            stringify!(tagSVTFCreateOptions),
            "::",
            stringify!(bGammaCorrection)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).sGammaCorrection) as usize - ptr as usize },
        78usize,
        concat!(
            "Offset of field: ",
            stringify!(tagSVTFCreateOptions),
            "::",
            stringify!(sGammaCorrection)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).bNormalMap) as usize - ptr as usize },
        82usize,
        concat!(
            "Offset of field: ",
            stringify!(tagSVTFCreateOptions),
            "::",
            stringify!(bNormalMap)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).KernelFilter) as usize - ptr as usize },
        83usize,
        concat!(
            "Offset of field: ",
            stringify!(tagSVTFCreateOptions),
            "::",
            stringify!(KernelFilter)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).HeightConversionMethod) as usize - ptr as usize },
        87usize,
        concat!(
            "Offset of field: ",
            stringify!(tagSVTFCreateOptions),
            "::",
            stringify!(HeightConversionMethod)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).NormalAlphaResult) as usize - ptr as usize },
        91usize,
        concat!(
            "Offset of field: ",
            stringify!(tagSVTFCreateOptions),
            "::",
            stringify!(NormalAlphaResult)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).bNormalMinimumZ) as usize - ptr as usize },
        95usize,
        concat!(
            "Offset of field: ",
            stringify!(tagSVTFCreateOptions),
            "::",
            stringify!(bNormalMinimumZ)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).sNormalScale) as usize - ptr as usize },
        96usize,
        concat!(
            "Offset of field: ",
            stringify!(tagSVTFCreateOptions),
            "::",
            stringify!(sNormalScale)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).bNormalWrap) as usize - ptr as usize },
        100usize,
        concat!(
            "Offset of field: ",
            stringify!(tagSVTFCreateOptions),
            "::",
            stringify!(bNormalWrap)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).bNormalInvertX) as usize - ptr as usize },
        101usize,
        concat!(
            "Offset of field: ",
            stringify!(tagSVTFCreateOptions),
            "::",
            stringify!(bNormalInvertX)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).bNormalInvertY) as usize - ptr as usize },
        102usize,
        concat!(
            "Offset of field: ",
            stringify!(tagSVTFCreateOptions),
            "::",
            stringify!(bNormalInvertY)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).bNormalInvertZ) as usize - ptr as usize },
        103usize,
        concat!(
            "Offset of field: ",
            stringify!(tagSVTFCreateOptions),
            "::",
            stringify!(bNormalInvertZ)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).bSphereMap) as usize - ptr as usize },
        104usize,
        concat!(
            "Offset of field: ",
            stringify!(tagSVTFCreateOptions),
            "::",
            stringify!(bSphereMap)
        )
    );
}
pub type SVTFCreateOptions = tagSVTFCreateOptions;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct VTFLibVTFFile {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct VTFLibVMTFile {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct VTFLibError {
    _unused: [u8; 0],
}
pub const tagVTFLibOption_VTFLIB_DXT_QUALITY: tagVTFLibOption = 0;
pub const tagVTFLibOption_VTFLIB_LUMINANCE_WEIGHT_R: tagVTFLibOption = 1;
pub const tagVTFLibOption_VTFLIB_LUMINANCE_WEIGHT_G: tagVTFLibOption = 2;
pub const tagVTFLibOption_VTFLIB_LUMINANCE_WEIGHT_B: tagVTFLibOption = 3;
pub const tagVTFLibOption_VTFLIB_BLUESCREEN_MASK_R: tagVTFLibOption = 4;
pub const tagVTFLibOption_VTFLIB_BLUESCREEN_MASK_G: tagVTFLibOption = 5;
pub const tagVTFLibOption_VTFLIB_BLUESCREEN_MASK_B: tagVTFLibOption = 6;
pub const tagVTFLibOption_VTFLIB_BLUESCREEN_CLEAR_R: tagVTFLibOption = 7;
pub const tagVTFLibOption_VTFLIB_BLUESCREEN_CLEAR_G: tagVTFLibOption = 8;
pub const tagVTFLibOption_VTFLIB_BLUESCREEN_CLEAR_B: tagVTFLibOption = 9;
pub const tagVTFLibOption_VTFLIB_FP16_HDR_KEY: tagVTFLibOption = 10;
pub const tagVTFLibOption_VTFLIB_FP16_HDR_SHIFT: tagVTFLibOption = 11;
pub const tagVTFLibOption_VTFLIB_FP16_HDR_GAMMA: tagVTFLibOption = 12;
pub const tagVTFLibOption_VTFLIB_UNSHARPEN_RADIUS: tagVTFLibOption = 13;
pub const tagVTFLibOption_VTFLIB_UNSHARPEN_AMOUNT: tagVTFLibOption = 14;
pub const tagVTFLibOption_VTFLIB_UNSHARPEN_THRESHOLD: tagVTFLibOption = 15;
pub const tagVTFLibOption_VTFLIB_XSHARPEN_STRENGTH: tagVTFLibOption = 16;
pub const tagVTFLibOption_VTFLIB_XSHARPEN_THRESHOLD: tagVTFLibOption = 17;
pub const tagVTFLibOption_VTFLIB_VMT_PARSE_MODE: tagVTFLibOption = 18;
pub type tagVTFLibOption = ::std::os::raw::c_int;
pub use self::tagVTFLibOption as VTFLibOption;
extern "C" {
    #[doc = "! Return the VTFLib version as an integer."]
    pub fn vlGetVersion() -> vlUInt;
}
extern "C" {
    #[doc = "! Return the VTFLib version as a string."]
    pub fn vlGetVersionString() -> *const vlChar;
}
extern "C" {
    #[doc = "! Return the specified option."]
    pub fn vlGetBoolean(Option: VTFLibOption) -> vlBool;
}
extern "C" {
    #[doc = "! Set the specified option."]
    pub fn vlSetBoolean(Option: VTFLibOption, bValue: vlBool);
}
extern "C" {
    #[doc = "! Return the specified option."]
    pub fn vlGetInteger(Option: VTFLibOption) -> vlInt;
}
extern "C" {
    #[doc = "! Set the specified option."]
    pub fn vlSetInteger(Option: VTFLibOption, iValue: vlInt);
}
extern "C" {
    #[doc = "! Return the specified option."]
    pub fn vlGetFloat(Option: VTFLibOption) -> vlSingle;
}
extern "C" {
    #[doc = "! Set the specified option."]
    pub fn vlSetFloat(Option: VTFLibOption, sValue: vlSingle);
}
extern "C" {
    pub fn vlCreateVTFFile() -> *mut VTFLibVTFFile;
}
extern "C" {
    pub fn vlDestroyVTFFile(VTFFile: *mut VTFLibVTFFile);
}
extern "C" {
    pub fn vlCreateVTFLibError() -> *mut VTFLibError;
}
extern "C" {
    pub fn vlDestroyVTFLibError(VTFLibError: *mut VTFLibError);
}
extern "C" {
    pub fn vlGetErrorMessage(VTFLibError: *const VTFLibError) -> *const vlChar;
}
extern "C" {
    pub fn vlImageCreateDefaultCreateStructure(VTFCreateOptions: *mut SVTFCreateOptions);
}
extern "C" {
    pub fn vlImageCreate(
        VTFFile: *mut VTFLibVTFFile,
        uiWidth: vlUInt,
        uiHeight: vlUInt,
        uiFrames: vlUInt,
        uiFaces: vlUInt,
        uiSlices: vlUInt,
        ImageFormat: VTFImageFormat,
        bThumbnail: vlBool,
        bMipmaps: vlBool,
        bNullImageData: vlBool,
        Error: *mut VTFLibError,
    ) -> vlBool;
}
extern "C" {
    pub fn vlImageCreateSingle(
        VTFFile: *mut VTFLibVTFFile,
        uiWidth: vlUInt,
        uiHeight: vlUInt,
        lpImageDataRGBA8888: *mut vlByte,
        VTFCreateOptions: *mut SVTFCreateOptions,
        Error: *mut VTFLibError,
    ) -> vlBool;
}
extern "C" {
    pub fn vlImageCreateMultiple(
        VTFFile: *mut VTFLibVTFFile,
        uiWidth: vlUInt,
        uiHeight: vlUInt,
        uiFrames: vlUInt,
        uiFaces: vlUInt,
        uiSlices: vlUInt,
        lpImageDataRGBA8888: *mut *mut vlByte,
        VTFCreateOptions: *mut SVTFCreateOptions,
        Error: *mut VTFLibError,
    ) -> vlBool;
}
extern "C" {
    pub fn vlImageIsLoaded(VTFFile: *const VTFLibVTFFile) -> vlBool;
}
extern "C" {
    pub fn vlImageLoad(
        VTFFile: *mut VTFLibVTFFile,
        cFileName: *const vlChar,
        bHeaderOnly: vlBool,
        Error: *mut VTFLibError,
    ) -> vlBool;
}
extern "C" {
    pub fn vlImageLoadLump(
        VTFFile: *mut VTFLibVTFFile,
        lpData: *const vlVoid,
        uiBufferSize: vlSize,
        bHeaderOnly: vlBool,
        Error: *mut VTFLibError,
    ) -> vlBool;
}
extern "C" {
    pub fn vlImageLoadProc(
        VTFFile: *mut VTFLibVTFFile,
        pUserData: *mut vlVoid,
        bHeaderOnly: vlBool,
        Error: *mut VTFLibError,
    ) -> vlBool;
}
extern "C" {
    pub fn vlImageSave(
        VTFFile: *const VTFLibVTFFile,
        cFileName: *const vlChar,
        Error: *mut VTFLibError,
    ) -> vlBool;
}
extern "C" {
    pub fn vlImageSaveLump(
        VTFFile: *const VTFLibVTFFile,
        lpData: *mut vlVoid,
        uiBufferSize: vlSize,
        uiSize: *mut vlSize,
        Error: *mut VTFLibError,
    ) -> vlBool;
}
extern "C" {
    pub fn vlImageSaveProc(
        VTFFile: *const VTFLibVTFFile,
        pUserData: *mut vlVoid,
        Error: *mut VTFLibError,
    ) -> vlBool;
}
extern "C" {
    pub fn vlImageGetHasImage(VTFFile: *const VTFLibVTFFile) -> vlUInt;
}
extern "C" {
    pub fn vlImageGetMajorVersion(VTFFile: *const VTFLibVTFFile) -> vlUInt;
}
extern "C" {
    pub fn vlImageGetMinorVersion(VTFFile: *const VTFLibVTFFile) -> vlUInt;
}
extern "C" {
    pub fn vlImageGetSize(VTFFile: *const VTFLibVTFFile) -> vlUInt;
}
extern "C" {
    pub fn vlImageGetWidth(VTFFile: *const VTFLibVTFFile) -> vlUInt;
}
extern "C" {
    pub fn vlImageGetHeight(VTFFile: *const VTFLibVTFFile) -> vlUInt;
}
extern "C" {
    pub fn vlImageGetDepth(VTFFile: *const VTFLibVTFFile) -> vlUInt;
}
extern "C" {
    pub fn vlImageGetFrameCount(VTFFile: *const VTFLibVTFFile) -> vlUInt;
}
extern "C" {
    pub fn vlImageGetFaceCount(VTFFile: *const VTFLibVTFFile) -> vlUInt;
}
extern "C" {
    pub fn vlImageGetMipmapCount(VTFFile: *const VTFLibVTFFile) -> vlUInt;
}
extern "C" {
    pub fn vlImageGetStartFrame(VTFFile: *const VTFLibVTFFile) -> vlUInt;
}
extern "C" {
    pub fn vlImageSetStartFrame(VTFFile: *mut VTFLibVTFFile, uiStartFrame: vlUInt);
}
extern "C" {
    pub fn vlImageGetFlags(VTFFile: *const VTFLibVTFFile) -> vlUInt;
}
extern "C" {
    pub fn vlImageSetFlags(VTFFile: *mut VTFLibVTFFile, uiFlags: vlUInt);
}
extern "C" {
    pub fn vlImageGetFlag(VTFFile: *const VTFLibVTFFile, ImageFlag: VTFImageFlag) -> vlBool;
}
extern "C" {
    pub fn vlImageSetFlag(VTFFile: *mut VTFLibVTFFile, ImageFlag: VTFImageFlag, bState: vlBool);
}
extern "C" {
    pub fn vlImageGetBumpmapScale(VTFFile: *const VTFLibVTFFile) -> vlSingle;
}
extern "C" {
    pub fn vlImageSetBumpmapScale(VTFFile: *mut VTFLibVTFFile, sBumpmapScale: vlSingle);
}
extern "C" {
    pub fn vlImageGetReflectivity(
        VTFFile: *const VTFLibVTFFile,
        sX: *mut vlSingle,
        sY: *mut vlSingle,
        sZ: *mut vlSingle,
    );
}
extern "C" {
    pub fn vlImageSetReflectivity(
        VTFFile: *mut VTFLibVTFFile,
        sX: vlSingle,
        sY: vlSingle,
        sZ: vlSingle,
    );
}
extern "C" {
    pub fn vlImageGetFormat(VTFFile: *const VTFLibVTFFile) -> VTFImageFormat;
}
extern "C" {
    pub fn vlImageGetData(
        VTFFile: *const VTFLibVTFFile,
        uiFrame: vlUInt,
        uiFace: vlUInt,
        uiSlice: vlUInt,
        uiMipmapLevel: vlUInt,
    ) -> *mut vlByte;
}
extern "C" {
    pub fn vlImageSetData(
        VTFFile: *mut VTFLibVTFFile,
        uiFrame: vlUInt,
        uiFace: vlUInt,
        uiSlice: vlUInt,
        uiMipmapLevel: vlUInt,
        lpData: *mut vlByte,
    );
}
extern "C" {
    pub fn vlImageGetHasThumbnail(VTFFile: *const VTFLibVTFFile) -> vlBool;
}
extern "C" {
    pub fn vlImageGetThumbnailWidth(VTFFile: *const VTFLibVTFFile) -> vlUInt;
}
extern "C" {
    pub fn vlImageGetThumbnailHeight(VTFFile: *const VTFLibVTFFile) -> vlUInt;
}
extern "C" {
    pub fn vlImageGetThumbnailFormat(VTFFile: *const VTFLibVTFFile) -> VTFImageFormat;
}
extern "C" {
    pub fn vlImageGetThumbnailData(VTFFile: *const VTFLibVTFFile) -> *mut vlByte;
}
extern "C" {
    pub fn vlImageSetThumbnailData(VTFFile: *mut VTFLibVTFFile, lpData: *mut vlByte);
}
extern "C" {
    pub fn vlImageGetSupportsResources(VTFFile: *const VTFLibVTFFile) -> vlBool;
}
extern "C" {
    pub fn vlImageGetResourceCount(VTFFile: *const VTFLibVTFFile) -> vlUInt;
}
extern "C" {
    pub fn vlImageGetResourceType(VTFFile: *const VTFLibVTFFile, uiIndex: vlUInt) -> vlUInt;
}
extern "C" {
    pub fn vlImageGetHasResource(VTFFile: *const VTFLibVTFFile, uiType: vlUInt) -> vlBool;
}
extern "C" {
    pub fn vlImageGetResourceData(
        VTFFile: *const VTFLibVTFFile,
        uiType: vlUInt,
        uiSize: *mut vlUInt,
        Error: *mut VTFLibError,
    ) -> *mut vlVoid;
}
extern "C" {
    pub fn vlImageSetResourceData(
        VTFFile: *mut VTFLibVTFFile,
        uiType: vlUInt,
        uiSize: vlUInt,
        lpData: *mut vlVoid,
        Error: *mut VTFLibError,
    ) -> *mut vlVoid;
}
extern "C" {
    pub fn vlImageGenerateMipmaps(
        VTFFile: *mut VTFLibVTFFile,
        uiFace: vlUInt,
        uiFrame: vlUInt,
        MipmapFilter: VTFMipmapFilter,
        SharpenFilter: VTFSharpenFilter,
        Error: *mut VTFLibError,
    ) -> vlBool;
}
extern "C" {
    pub fn vlImageGenerateAllMipmaps(
        VTFFile: *mut VTFLibVTFFile,
        MipmapFilter: VTFMipmapFilter,
        SharpenFilter: VTFSharpenFilter,
        Error: *mut VTFLibError,
    ) -> vlBool;
}
extern "C" {
    pub fn vlImageGenerateThumbnail(VTFFile: *mut VTFLibVTFFile, Error: *mut VTFLibError)
        -> vlBool;
}
extern "C" {
    pub fn vlImageGenerateNormalMap(
        VTFFile: *mut VTFLibVTFFile,
        uiFrame: vlUInt,
        KernelFilter: VTFKernelFilter,
        HeightConversionMethod: VTFHeightConversionMethod,
        NormalAlphaResult: VTFNormalAlphaResult,
        Error: *mut VTFLibError,
    ) -> vlBool;
}
extern "C" {
    pub fn vlImageGenerateAllNormalMaps(
        VTFFile: *mut VTFLibVTFFile,
        KernelFilter: VTFKernelFilter,
        HeightConversionMethod: VTFHeightConversionMethod,
        NormalAlphaResult: VTFNormalAlphaResult,
        Error: *mut VTFLibError,
    ) -> vlBool;
}
extern "C" {
    pub fn vlImageGenerateSphereMap(VTFFile: *mut VTFLibVTFFile, Error: *mut VTFLibError)
        -> vlBool;
}
extern "C" {
    pub fn vlImageComputeReflectivity(
        VTFFile: *mut VTFLibVTFFile,
        Error: *mut VTFLibError,
    ) -> vlBool;
}
extern "C" {
    pub fn vlImageGetImageFormatInfo(ImageFormat: VTFImageFormat) -> *const SVTFImageFormatInfo;
}
extern "C" {
    pub fn vlImageGetImageFormatInfoEx(
        ImageFormat: VTFImageFormat,
        VTFImageFormatInfo: *mut SVTFImageFormatInfo,
    ) -> vlBool;
}
extern "C" {
    pub fn vlImageComputeImageSize(
        uiWidth: vlUInt,
        uiHeight: vlUInt,
        uiDepth: vlUInt,
        uiMipmaps: vlUInt,
        ImageFormat: VTFImageFormat,
    ) -> vlUInt;
}
extern "C" {
    pub fn vlImageComputeMipmapCount(uiWidth: vlUInt, uiHeight: vlUInt, uiDepth: vlUInt) -> vlUInt;
}
extern "C" {
    pub fn vlImageComputeMipmapDimensions(
        uiWidth: vlUInt,
        uiHeight: vlUInt,
        uiDepth: vlUInt,
        uiMipmapLevel: vlUInt,
        uiMipmapWidth: *mut vlUInt,
        uiMipmapHeight: *mut vlUInt,
        uiMipmapDepth: *mut vlUInt,
    );
}
extern "C" {
    pub fn vlImageComputeMipmapSize(
        uiWidth: vlUInt,
        uiHeight: vlUInt,
        uiDepth: vlUInt,
        uiMipmapLevel: vlUInt,
        ImageFormat: VTFImageFormat,
    ) -> vlUInt;
}
extern "C" {
    pub fn vlImageConvertToRGBA8888(
        lpSource: *mut vlByte,
        lpDest: *mut vlByte,
        uiWidth: vlUInt,
        uiHeight: vlUInt,
        SourceFormat: VTFImageFormat,
        Error: *mut VTFLibError,
    ) -> vlBool;
}
extern "C" {
    pub fn vlImageConvertFromRGBA8888(
        lpSource: *mut vlByte,
        lpDest: *mut vlByte,
        uiWidth: vlUInt,
        uiHeight: vlUInt,
        DestFormat: VTFImageFormat,
        Error: *mut VTFLibError,
    ) -> vlBool;
}
extern "C" {
    pub fn vlImageConvert(
        lpSource: *mut vlByte,
        lpDest: *mut vlByte,
        uiWidth: vlUInt,
        uiHeight: vlUInt,
        SourceFormat: VTFImageFormat,
        DestFormat: VTFImageFormat,
        Error: *mut VTFLibError,
    ) -> vlBool;
}
extern "C" {
    pub fn vlImageConvertToNormalMap(
        lpSourceRGBA8888: *mut vlByte,
        lpDestRGBA8888: *mut vlByte,
        uiWidth: vlUInt,
        uiHeight: vlUInt,
        KernelFilter: VTFKernelFilter,
        HeightConversionMethod: VTFHeightConversionMethod,
        NormalAlphaResult: VTFNormalAlphaResult,
        bMinimumZ: vlByte,
        sScale: vlSingle,
        bWrap: vlBool,
        bInvertX: vlBool,
        bInvertY: vlBool,
        Error: *mut VTFLibError,
    ) -> vlBool;
}
extern "C" {
    pub fn vlImageResize(
        lpSourceRGBA8888: *mut vlByte,
        lpDestRGBA8888: *mut vlByte,
        uiSourceWidth: vlUInt,
        uiSourceHeight: vlUInt,
        uiDestWidth: vlUInt,
        uiDestHeight: vlUInt,
        ResizeFilter: VTFMipmapFilter,
        SharpenFilter: VTFSharpenFilter,
        Error: *mut VTFLibError,
    ) -> vlBool;
}
extern "C" {
    pub fn vlImageCorrectImageGamma(
        lpImageDataRGBA8888: *mut vlByte,
        uiWidth: vlUInt,
        uiHeight: vlUInt,
        sGammaCorrection: vlSingle,
    );
}
extern "C" {
    pub fn vlImageComputeImageReflectivity(
        lpImageDataRGBA8888: *mut vlByte,
        uiWidth: vlUInt,
        uiHeight: vlUInt,
        sX: *mut vlSingle,
        sY: *mut vlSingle,
        sZ: *mut vlSingle,
    );
}
extern "C" {
    pub fn vlImageFlipImage(lpImageDataRGBA8888: *mut vlByte, uiWidth: vlUInt, uiHeight: vlUInt);
}
extern "C" {
    pub fn vlImageMirrorImage(lpImageDataRGBA8888: *mut vlByte, uiWidth: vlUInt, uiHeight: vlUInt);
}
